name: Status Report Action
description: |
  This action provides a status report from a reusable GitHub action or workflow as a PR comment. The report
  is updated in place everytime it is published.

inputs:
  body:
    description: |
      The report content.
    required: true
  repository:
    description: |
      The repository of the action that is publishing the report. Defaults to env.status-report-action-repository.
    required: false
  issue-number:
    description: |
      The issue where to post the comment. This defaults to the PR number on pull request events,
      otherwise, it should be provided.
    required: true
    default: ${{ github.event.pull_request.number }}
outputs:
  comment-id:
    description: The comment ID.
    value: ${{ steps.upsert-comment.outputs.comment-id }}

runs:
  using: "composite"
  steps:
    - id: infer-variables
      name: Infer variables
      shell: bash
      run: |
        if test -z "${{ inputs.repository }}"; then
          repository="${{ env.status-report-action-repository }}"
        else
          repository="${{ inputs.repository }}"
        fi
        
        if test -z "${repository}"; then
          echo "Must provide a value for the repository input"
          exit 1
        fi
                
        title="${repository#*/}"
        link="https://github.com/${repository}"
        
        echo "::debug::inferred repository ${repository}"
        echo "::debug::inferred title ${title}"
        echo "::debug::inferred link ${link}"
        echo "repository=${repository}" >> "${GITHUB_OUTPUT}"
        echo "title=${title}" >> "${GITHUB_OUTPUT}"
        echo "link=${link}" >> "${GITHUB_OUTPUT}"
    - id: upsert-comment
      uses: infrastructure-blocks/upsert-comment-action@v1
      with:
        issue-number: ${{ inputs.issue-number }}
        body: |
          [${{ steps.infer-variables.outputs.title }}](${{ steps.infer-variables.outputs.link }}) Report
          ---
          ${{ inputs.body }}
        matches: '^\[${{ steps.infer-variables.outputs.title }}\]\(${{ steps.infer-variables.outputs.link }}\) Report'
