name: Self test

on:
  pull_request: ~

permissions:
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  self-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - id: composite-action
        uses: ./
        with:
          title: self-test
          body: |
            Seems like it works.
            And supports multiline comments.
            Plus markdown:
            - [ ] No finished
            - [x] Finished
      - run: |
          echo ${{ steps.composite-action.outputs.example-output }}
