name: Self test

on:
  pull_request: ~
  push: ~

permissions:
  pull-requests: write
  issues: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  status-report-action-repository: ${{ github.repository }}

jobs:
  self-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - if: ${{ github.event_name == 'pull_request' }}
        id: pr-action
        name: Post PR Comment
        uses: ./
        with:
          repository: ${{ github.repository }}
          body: |
            The status:
            - [x] PR
            - [ ] Push
      - if: ${{ github.event_name == 'pull_request' }}
        name: Show Outputs
        run: |
          echo ${{ steps.pr-action.outputs.comment-id }}
      - if: ${{ github.event_name == 'push' }}
        id: push-action
        name: Post Issue Comment
        uses: ./
        with:
          issue-number: ${{ vars.TEST_ISSUE_PUSH_TESTS }}
          body: |
            The status:
            - [ ] PR
            - [x] Push
      - if: ${{ github.event_name == 'push' }}
        name: Show Outputs
        run: |
          echo "comment ID is: ${{ steps.push-action.outputs.comment-id }}"
      - if: ${{ github.event_name == 'push' }}
        id: clear-missing-report
        name: Clear Missing Report
        uses: ./
        with:
          mode: clear
          issue-number: ${{ vars.TEST_ISSUE_CLEAR_TESTS }}
      - if: ${{ github.event_name == 'push' }}
        name: Show outputs
        run: |
          echo -e "${{ toJson(steps.clear-missing-report.outputs) }}"
      - if: ${{ github.event_name == 'push' }}
        name: Post Issue Comment For Removal
        uses: ./
        with:
          issue-number: ${{ vars.TEST_ISSUE_CLEAR_TESTS }}
          body: |
            Look at me! You ain't gonna sees me for long!
      - if: ${{ github.event_name == 'push' }}
        id: clear-existing-report
        name: Clear Existing Report
        uses: ./
        with:
          mode: clear
          issue-number: ${{ vars.TEST_ISSUE_CLEAR_TESTS }}
      - if: ${{ github.event_name == 'push' }}
        name: Show outputs
        run: |
          echo -e "${{ toJson(steps.clear-existing-report.outputs) }}"
