name: Self Test

on:
  pull_request: ~
  push: ~

permissions:
  pull-requests: write
  issues: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  status-report-action-repository: ${{ github.repository }}

jobs:
  self-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - if: ${{ github.event_name == 'pull_request' }}
        name: Post PR comment
        id: pr-action
        uses: ./
        with:
          repository: ${{ github.repository }}
          body: |
            The status:
            - [x] PR
            - [ ] Push
      - if: ${{ github.event_name == 'pull_request' }}
        name: Show outputs
        env:
          OUTPUTS: ${{ toJson(steps.pr-action.outputs) }}
        run: |
          echo "${OUTPUTS}"
      - if: ${{ github.event_name == 'push' }}
        name: Post issue comment
        id: push-action
        uses: ./
        with:
          issue-number: ${{ vars.TEST_ISSUE_PUSH_TESTS }}
          body: |
            The status:
            - [ ] PR
            - [x] Push
      - if: ${{ github.event_name == 'push' }}
        name: Show outputs
        env:
          OUTPUTS: ${{ toJson(steps.push-action.outputs) }}
        run: |
          echo "${OUTPUTS}"
      - if: ${{ github.event_name == 'push' }}
        name: Clear missing report
        id: clear-missing-report
        uses: ./
        with:
          mode: clear
          issue-number: ${{ vars.TEST_ISSUE_CLEAR_TESTS }}
      - if: ${{ github.event_name == 'push' }}
        name: Show outputs
        env:
          OUTPUTS: ${{ toJson(steps.clear-missing-report.outputs) }}
        run: |
          echo "${OUTPUTS}"
      - if: ${{ github.event_name == 'push' }}
        name: Post Issue Comment For Removal
        uses: ./
        with:
          issue-number: ${{ vars.TEST_ISSUE_CLEAR_TESTS }}
          body: |
            Look at me! You ain't gonna sees me for long!
      - if: ${{ github.event_name == 'push' }}
        name: Clear existing report
        id: clear-existing-report
        uses: ./
        with:
          mode: clear
          issue-number: ${{ vars.TEST_ISSUE_CLEAR_TESTS }}
      - if: ${{ github.event_name == 'push' }}
        name: Show outputs
        env:
          OUTPUTS: ${{ toJson(steps.clear-existing-report.outputs) }}
        run: |
          echo "${OUTPUTS}"
